apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: resume-builder-secrets
  namespace: resume-builder
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: resume-builder-secrets   # k8s Secret name pods will reference
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: /tf-practice/dev/db-credentials
        property: host
    - secretKey: DB_USERNAME
      remoteRef:
        key: /tf-practice/dev/db-credentials
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /tf-practice/dev/db-credentials
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: /tf-practice/dev/jwt-secret
        property: secret
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: /tf-practice/dev/google-oauth
        property: client_id
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: /tf-practice/dev/google-oauth
        property: client_secret