apiVersion: v1
kind: Service
metadata:
  name: {{ include "resume-builder-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "resume-builder-db.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "resume-builder-db.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
