apiVersion: v1
kind: Service
metadata:
  name: {{ include "resume-builder-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "resume-builder-ui.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "resume-builder-ui.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
